### ISSUE TITLE
Encoding Issue

### ISSUE THREAD

**Issue by zetas** [tweekmonster/tmux2html#1]
Hi, I really wanted to use this to display the processing of my system to users in realtime but it appears there's some kind of encoding issue when I run with multiple grabs over time (i'm not really 100% clear how to enable continuous animations in the html, i just ran it with --duration 5 to see what happened but i tried --duration 0 --interval 1 and got the same result)

Here's what I get when I run them:

![image](https://cloud.githubusercontent.com/assets/1036810/14150277/56ab6cf6-f676-11e5-90bc-2a32bcd2b16e.png)

**Comment by tweekmonster** [comment]
Hmm.  What version of Python is this?  And, unfortunately you can't get realtime since the results are compiled after the recording has finished.  What you can do is use something like `watch -n 0.5 tmux2html -o output.html` which will write a new file every 500ms.

**Comment by tweekmonster** [comment]
@zetas Nevermind, I see what's going on.  It's a Python 2 issue.  I'll have a fix up shortly.

**Comment by tweekmonster** [comment]
@zetas Uploaded the fixed version to pypi.  Thanks for reporting!

**Comment by zetas** [comment]
Thanks @tweekmonster
