### ISSUE TITLE
Animations Fail To Load Under Firefox

### ISSUE THREAD

**Issue by fundamental** [tweekmonster/tmux2html#10]
Using firefox 38.7.1 animations do not render. Opening up the console I can see:
"InvalidCharacterError: String contains an invalid character"

The line number and column correspond to the start of the minified javascript and no other errors are displayed. All other types (streams/static captures) appear to render fine.
I attempted to build a version of the animate.html template without the minification to make more sense out of it, but the node package ecosystem had other ideas.

**Comment by tweekmonster** [comment]
I'm away from my workstation at the moment. But, that error originated from `atob` when I was using line breaks in the base64 string.  Maybe it has something to do with the leading newline after the script tag?

**Comment by fundamental** [comment]
No problem.

It doesn't look like changing linebreaks in the generated file fixes things. Throwing a console.log(e) before the atob(e) call shows that e is undefined, which is presumably not the value that was expected.

**Comment by tweekmonster** [comment]
I bet if you changed `innerText` to `textContent` it'll work in Firefox.  I'll look into it more when I get back.

**Comment by fundamental** [comment]
Yep, that fixes the issue. There's a chance you might just be a javascript wizard.

**Comment by tweekmonster** [comment]
An update is inbound.  This incidentally fixed the scrollable renders, too.  Thanks!

> There's a chance you might just be a javascript wizard.

I wish!  Those guys are smooth with the ladies.
