### ISSUE TITLE
dies when closing pane

### ISSUE THREAD

**Issue by faxm0dem** [tweekmonster/tmux2html#12]
I'm recording using:

```
☠ tmux2html -o /tmp/realtime.html 4 --duration 0 --interval 0.1
```

When closing a pane in the window, tmux2html dies with following message:

```
can't find pane %38
```

**Comment by tweekmonster** [comment]
Thanks, I'll take a look!

**Comment by tweekmonster** [comment]
tmux2html is updated on pypi now.
