### ISSUE TITLE
Request: Streaming Output

### ISSUE THREAD

**Issue by zetas** [tweekmonster/tmux2html#2]
I know this is probably a huge request and may be outside the scope for this project but having an html/js file that has a stream of the tmux output would be a gamechanger. You added a snippet to the bug I submitted using watch on an interval. Would it be difficult to modify the code to output the updated results every interval and add in a javascript snippet to refresh the page every x seconds?

**Comment by tweekmonster** [comment]
Ah, now that makes more sense.  I said the only limit is our imagination and yours has no limit, pal!  :sparkles:

I think this will be easy enough.

**Comment by tweekmonster** [comment]
@zetas I added what you requested and updated pypi.  I updated the README (particularly the notes section) to explain limitations.  Feel free to reopen this issue if you find something wrong with it.

**Comment by tweekmonster** [comment]
Side note: this isn't real time at all, but it's still cool as hell if you ask me.  It might be worth making a separate project for realtime streaming.
