### ISSUE TITLE
Documentation: Add references to similar projects

### ISSUE THREAD

**Issue by faxm0dem** [tweekmonster/tmux2html#4]
like [gotty](/yudai/gotty) or [asciinema](/asciinema/asciinema)

awesome tool thanks!

**Comment by tweekmonster** [comment]
Thanks @faxm0dem.  I didn't know about gotty :open_mouth:.  I need to give it a try.  I'll add them to the README a little later.  I feel like there was one other tool similar asciinema but I can't think of the name.
