### ISSUE TITLE
Examples font is not monospace

### ISSUE THREAD

**Issue by ahmetb** [tweekmonster/tmux2html#5]
I have a mac and the examples render in a sans-serif font rather than monospace on Chrome.

**Comment by tweekmonster** [comment]
Hmm.  Might be one of the Powerline or Nerd fonts in the stack.  Do you have a non-monospace version of one of those fonts?  Reference here: https://github.com/tweekmonster/tmux2html/blob/master/tmux2html/main.py#L50-L107

Hate to admit it, but I didn't test all of those.  I wrote a script to extract the family names from the font files.

Can you also confirm that it's all text that's not monospace?  A friend who uses a patched version of Source Code Pro to include the Kibitaki font also had issues.  Everything was monospace except for narrow glyphs like `i` and `l`.  Example of the issue he's having:

![screen-shot-2016-03-31-10-39-02](https://cloud.githubusercontent.com/assets/111942/14183469/82a9be7a-f73e-11e5-9700-10133ac24fe5.png)

**Comment by tweekmonster** [comment]
@ahmetalpbalkan did you happen to look into this?

I discovered that my friend's issue has to do with font ligatures.  The fix for it is to add this style to the `pre` tag: `font-variant-ligatures: no-common-ligatures;`.  Hopefully that's all your issue is.

**Comment by ahmetb** [comment]
i don't have those fonts but `monospace` fallback should be working but it isn't.

here's the whatfont output:

![image](https://cloud.githubusercontent.com/assets/159209/14211791/cd82a636-f7e4-11e5-96b7-0a280ffd79fa.png)

**Comment by ahmetb** [comment]
hah turns out I have the powerline fonts. I removed Arimo and everything worked fine. I guess it was broken.

**Comment by tweekmonster** [comment]
@ahmetalpbalkan Woah not so fast!  WhatFont works for you in the examples?  It doesn't work for me.

> hah turns out I have the powerline fonts. I removed Arimo and everything worked fine. I guess it was broken.

Ah okay!  You might've did an accidental install from one of the 'source' or 'sample' fonts.  I'll have to see if Arimo is actually monospace and remove it if not.
